/**
 * GENERATED by scripts/styleguide-manifest.mjs — do not edit by hand.
 *
 * Maps every `data-handoff-component` hint declared in the design-system
 * manifest to its styleguide section id. Run `node scripts/styleguide-manifest.mjs`
 * to regenerate; `--check` fails CI when this file is stale.
 */
export const GENERATED_SECTION_BY_HINT: Record<string, string> = {
  "accordion": "accordion",
  "accordion-content": "accordion",
  "accordion-item": "accordion",
  "accordion-trigger": "accordion",
  "action-button": "action-button",
  "badge": "badge",
  "button": "button",
  "camera-toggle": "camera-toggle",
  "card-actions": "card-actions",
  "card-closure": "card-closure",
  "card-details": "card-details",
  "card-header": "card-header",
  "card-log": "card-log",
  "card-media": "card-media",
  "card-sensors": "card-sensors",
  "copy-button": "copy-button",
  "device-card": "device-card",
  "device-row": "device-card",
  "device-row-details": "device-card",
  "device-row-header": "device-card",
  "device-type-group": "devices-panel",
  "devices-panel": "devices-panel",
  "devices-panel-header": "devices-panel",
  "filter-bar": "filter-bar",
  "map-marker": "map-markers",
  "map-markers": "map-markers",
  "new-updates": "new-updates",
  "split-action": "split-action",
  "status-chip": "badge",
  "target-card": "target-card",
  "telemetry": "telemetry",
};
