/**
 * Co-located doc module for the MapMarker block — the composable tactical
 * marker (surface / ring / glyph / glow / overlays) driven by
 * resolveMarkerStyle(). Meta + anatomy live in `registry/manifest.json`.
 */
import { useState } from 'react';
import { Badge } from '@/shared/components/ui/badge';
import { Button } from '@/shared/components/ui/button';
import { Copy, Check } from '@/lib/icons/central';
import {
  MapMarker,
  resolveMarkerStyle,
  resolveAssetMarkerStyle,
  resolveTargetMarkerStyle,
  targetAffiliation,
  resolveThreatGlyph,
  markerLayerClasses,
  MARKER_LAYERS,
  ASSET_HEALTHS,
  ASSET_HEALTH_LABELS,
  AFFILIATION_LABELS,
  INTERACTION_STATE_LABELS,
  SEVERITY_ORDER,
  SEVERITY_LABEL,
  SEVERITY_COLOR,
  SEVERITY_PULSE,
  UNKNOWN_GRAY,
  type Affiliation,
  type InteractionState,
  type TargetStateInput,
  type Severity,
} from '@/primitives';
import { DroneCardIcon, UnknownIcon, CarIcon, TankIcon, TruckIcon, DroneIcon, MissileIcon } from '@/primitives/MapIcons';
import { SensorIcon } from '@/app/components/tacticalIcons';
import mapMarkerSrc from '@/primitives/MapMarker.tsx?raw';
import markerStylesSrc from '@/primitives/markerStyles.ts?raw';
import markerGlyphsSrc from '@/primitives/markerGlyphs.tsx?raw';
import markerTailwindSrc from '@/primitives/markerTailwind.ts?raw';
import urgencySrc from '@/primitives/urgency.ts?raw';
import type { ComponentDocModule } from '../registry/types';

const AFFS: Affiliation[] = ['friendly', 'hostile'];

// ── Layer anatomy (interactive) ─────────────────────────────────────────
//
// Hovering a layer row drives MapMarker's `highlightLayer` prop (dims every
// other layer on the live preview). Each row's "Copy CSS" button copies the
// Tailwind class string that reproduces that layer — generated by
// `markerLayerClasses` from the exact style object the preview renders, so
// the copyable recipe can never drift from the pixels.

const ANATOMY_STATES: InteractionState[] = ['default', 'hovered', 'selected', 'disabled'];
// Offline is listed for completeness but not selectable in the anatomy demo.
const ANATOMY_DISABLED_STATES: InteractionState[] = ['disabled'];

/** Selectable control chip riding the shared Badge component. */
function ControlBadge({
  active,
  disabled = false,
  onClick,
  children,
}: {
  active: boolean;
  disabled?: boolean;
  onClick: () => void;
  children: React.ReactNode;
}) {
  return (
    <Badge asChild variant={active ? 'default' : 'ghost'}>
      <button
        type="button"
        disabled={disabled}
        onClick={onClick}
        className="cursor-pointer disabled:cursor-not-allowed disabled:opacity-40"
      >
        {children}
      </button>
    </Badge>
  );
}

/** Labeled copy affordance — copies the layer's Tailwind class string. */
function CopyCssButton({ value, title }: { value: string; title: string }) {
  const [copied, setCopied] = useState(false);
  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(value);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 1500);
    } catch {
      // clipboard unavailable — leave the idle state
    }
  };
  return (
    <Button
      type="button"
      variant="ghost"
      size="sm"
      disabled={!value}
      onClick={handleCopy}
      aria-label={copied ? 'Copied' : `Copy ${title} Tailwind classes`}
      className="h-6 gap-1 px-2 text-2xs text-slate-10 hover:text-slate-12"
    >
      {copied ? <Check className="size-3" /> : <Copy className="size-3" />}
      {copied ? 'Copied' : 'Copy CSS'}
    </Button>
  );
}

function LayerAnatomyExample() {
  const [hoveredLayer, setHoveredLayer] = useState<number | null>(null);
  const [previewHovered, setPreviewHovered] = useState(false);
  const [state, setState] = useState<InteractionState>('default');
  const [aff, setAff] = useState<Affiliation>('hostile');

  const style = resolveMarkerStyle(state, aff);
  const classes = markerLayerClasses(style, { surfaceSize: 72, ringSize: 56 });

  return (
    <div className="w-full space-y-4">
      {/* Controls — the copied class strings update with the resolved style */}
      <div className="flex flex-wrap items-center gap-x-4 gap-y-2">
        <div className="flex items-center gap-1.5">
          <span className="text-2xs uppercase tracking-wide text-slate-9">State</span>
          {ANATOMY_STATES.map((s) => (
            <ControlBadge
              key={s}
              active={state === s}
              disabled={ANATOMY_DISABLED_STATES.includes(s)}
              onClick={() => setState(s)}
            >
              {INTERACTION_STATE_LABELS[s]}
            </ControlBadge>
          ))}
        </div>
        <div className="flex items-center gap-1.5">
          <span className="text-2xs uppercase tracking-wide text-slate-9">Affiliation</span>
          {AFFS.map((a) => (
            <ControlBadge key={a} active={aff === a} onClick={() => setAff(a)}>
              {AFFILIATION_LABELS[a]}
            </ControlBadge>
          ))}
        </div>
      </div>

      <div className="grid gap-4 lg:grid-cols-[260px_minmax(0,1fr)]">
        {/* Live preview — highlightLayer dims all but the hovered layer;
            hovering the panel hides the hint without pulsing the marker. */}
        <div
          className="relative flex items-center justify-center rounded-xl border border-white/10 p-8"
          style={{ background: 'radial-gradient(circle at 50% 50%, rgba(255,255,255,0.25) 0%, rgba(0,0,0,1) 61%)' }}
          onMouseEnter={() => setPreviewHovered(true)}
          onMouseLeave={() => setPreviewHovered(false)}
        >
          <MapMarker
            icon={<SensorIcon size={48} outlined fill={style.glyphColor} />}
            style={style}
            surfaceSize={72}
            ringSize={56}
            label="Tooltip"
            showLabel
            highlightLayer={hoveredLayer}
            pulse={aff === 'hostile' && state !== 'disabled' && state !== 'expired'}
          />
          <span
            aria-hidden="true"
            className={`pointer-events-none absolute bottom-2 left-1/2 -translate-x-1/2 whitespace-nowrap text-2xs text-slate-9 transition-opacity duration-200 ${
              previewHovered ? 'opacity-0' : 'opacity-100'
            }`}
          >
            Hover to inspect layers
          </span>
        </div>

        {/* Layer list — hover to isolate, copy the Tailwind recipe per layer */}
        <div className="w-full space-y-1.5">
          {MARKER_LAYERS.map(({ layer, key, title }) => {
            const tw = classes[key];
            return (
              <div
                key={key}
                className={`flex items-center justify-between gap-2 rounded-lg border px-3 py-2 transition-colors duration-200 ${
                  hoveredLayer === layer
                    ? 'border-white/20 bg-white/[0.06]'
                    : 'border-white/[0.06] bg-white/[0.03]'
                }`}
                onMouseEnter={() => setHoveredLayer(layer)}
                onMouseLeave={() => setHoveredLayer(null)}
              >
                <span className="text-xs font-semibold text-slate-11">
                  <span className="mr-1.5 font-mono text-2xs text-slate-9">{layer}</span>
                  {title}
                </span>
                <CopyCssButton value={tw} title={title} />
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}

// ── Severity & urgency (targets) ────────────────────────────────────────
//
// Backend-contract fixtures: each tile feeds a plain serializable
// `TargetStateInput` through the production resolvers, exactly like a live
// backend payload would.

const SEVERITY_FIXTURES: Record<Severity, TargetStateInput> = {
  CRITICAL: { status: 'event', entityStage: 'classified', classifiedType: 'car' },
  HIGH: { status: 'detection', entityStage: 'classified', classifiedType: 'car' },
  MEDIUM: { status: 'detection', entityStage: 'classified', classifiedType: 'car', affiliation: 'possibleThreat' },
  LOW: { status: 'event_resolved', classifiedType: 'car' },
};

export const mapMarkersDoc: ComponentDocModule = {
  id: 'map-markers',
  // The usage snippet is a dependency-free handoff starter — its comments
  // carry the layer-by-layer instructions, so keep them in the preview.
  usageKeepComments: true,
  source: mapMarkerSrc,
  relatedFiles: [
    { file: 'markerStyles.ts', code: markerStylesSrc },
    { file: 'urgency.ts', code: urgencySrc },
    { file: 'markerGlyphs.tsx', code: markerGlyphsSrc },
    { file: 'markerTailwind.ts', code: markerTailwindSrc },
  ],
  usage: `export function TacticalMarker({
  glyph,               // your entity SVG, inherits the urgency color
  label = "TRK-4471",
  showLabel = false,
  hovered = false,     // hovered/selected: white ring + inner glow
}: {
  glyph: React.ReactNode
  label?: string
  showLabel?: boolean
  hovered?: boolean
}) {
  return (
    <div className="relative flex items-center justify-center" style={{ width: 72, height: 72 }}>
      {/* 1 Surface — frosted disc behind the glyph */}
      <div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 size-[72px] rounded-full bg-[rgba(255,255,255,0.1)] backdrop-blur-[1px]" />

      {/* 2 Ring — the urgency channel (hostile red; hovered flips it white) */}
      <div
        className={
          "absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 pointer-events-none z-[1] size-[56px] rounded-full border-[2px] border-solid " +
          (hovered ? "border-[rgba(255,255,255,1)]" : "border-[rgba(252,69,64,1)]")
        }
      />

      {/* 4 Inner Glow — interaction emphasis, only while hovered/selected */}
      {hovered && (
        <div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 pointer-events-none z-[2] rounded-full size-[34px] bg-[rgba(252,69,64,0.4)]" />
      )}

      {/* 3 Glyph — entity identity, painted in the urgency color */}
      <div className="relative z-[3] flex items-center justify-center text-[#fc4540]">
        {glyph}
      </div>

      {/* 5 Overlays — label pill floating at the marker's top-right */}
      {showLabel && (
        <div
          className="absolute z-[7] whitespace-nowrap rounded bg-black/60 px-2 py-[3px] text-xs font-medium text-white backdrop-blur-[12px] shadow-[0_0_0_1px_rgba(255,255,255,0.1),0_4px_12px_rgba(0,0,0,0.4)]"
          style={{ left: 42, bottom: 38 }}
        >
          {label}
        </div>
      )}
    </div>
  )
}`,
  examples: [
    {
      id: 'layer-anatomy',
      title: 'Layer anatomy — copy Tailwind per layer',
      code: `import { useState } from "react"
import {
  MapMarker,
  resolveMarkerStyle,
  markerLayerClasses,
  MARKER_LAYERS,
  type Affiliation,
  type InteractionState,
} from "@/primitives"

function LayerAnatomy() {
  const [hoveredLayer, setHoveredLayer] = useState<number | null>(null)
  const [state, setState] = useState<InteractionState>("default")
  const [aff, setAff] = useState<Affiliation>("hostile")

  // Resolve the style once; markerLayerClasses turns it into the
  // per-layer Tailwind recipe (surface / ring / glyph / innerGlow / overlays).
  const style = resolveMarkerStyle(state, aff)
  const classes = markerLayerClasses(style, { surfaceSize: 72, ringSize: 56 })

  return (
    <>
      {/* Live preview — highlightLayer dims every other layer */}
      <MapMarker
        icon={<YourGlyph fill={style.glyphColor} />}
        style={style}
        surfaceSize={72}
        ringSize={56}
        label="Tooltip"
        showLabel
        highlightLayer={hoveredLayer}
        pulse={aff === "hostile" && state !== "disabled" && state !== "expired"}
      />

      {/* Layer list — hover isolates, the button copies the Tailwind string */}
      {MARKER_LAYERS.map(({ layer, key, title }) => (
        <div
          key={key}
          onMouseEnter={() => setHoveredLayer(layer)}
          onMouseLeave={() => setHoveredLayer(null)}
        >
          {layer} {title}
          <button onClick={() => navigator.clipboard.writeText(classes[key])}>
            Copy CSS
          </button>
        </div>
      ))}
    </>
  )
}`,
      render: () => <LayerAnatomyExample />,
    },
    {
      id: 'affiliations',
      title: 'Affiliations',
      code: `{AFFILIATIONS.map((aff) => (
  <MapMarker
    icon={<DroneCardIcon size={20} />}
    style={resolveMarkerStyle("default", aff)}
    surfaceSize={36}
    ringSize={28}
    pulse={aff === "hostile"}
  />
))}`,
      render: () => (
        <div className="flex items-end gap-8">
          {AFFS.map((aff) => {
            const style = resolveMarkerStyle('default', aff);
            return (
              <div key={aff} className="flex flex-col items-center gap-2">
                <MapMarker
                  icon={<span style={{ color: style.glyphColor }}><DroneCardIcon size={20} /></span>}
                  style={style}
                  surfaceSize={36}
                  ringSize={28}
                  pulse={aff === 'hostile'}
                />
                <span className="text-2xs text-slate-9">{AFFILIATION_LABELS[aff]}</span>
              </div>
            );
          })}
        </div>
      ),
    },
    {
      id: 'interaction',
      title: 'Interaction states',
      code: `<MapMarker style={resolveMarkerStyle("default", "hostile")} pulse … />
<MapMarker style={resolveMarkerStyle("selected", "hostile")} pulse … />
<MapMarker style={resolveMarkerStyle("expired", "hostile")} pulse={false} … />`,
      render: () => (
        <div className="flex items-end gap-8">
          {(['default', 'selected', 'expired'] as const).map((state) => {
            const style = resolveMarkerStyle(state, 'hostile');
            return (
              <div key={state} className="flex flex-col items-center gap-2">
                <MapMarker
                  icon={<span style={{ color: style.glyphColor }}><DroneCardIcon size={20} /></span>}
                  style={style}
                  surfaceSize={36}
                  ringSize={28}
                  pulse={state !== 'expired'}
                />
                <span className="text-2xs text-slate-9">{state}</span>
              </div>
            );
          })}
        </div>
      ),
    },
    {
      id: 'asset-health',
      title: 'Friendly-asset health',
      code: `// Binary model: error paints the resting ring red; the reason rides
// the label/tooltip. Interaction still flips the ring white.
<MapMarker style={resolveAssetMarkerStyle("ok")} … />
<MapMarker style={resolveAssetMarkerStyle("error")} … />`,
      render: () => (
        <div className="flex items-end gap-8">
          {ASSET_HEALTHS.map((health) => {
            const style = resolveAssetMarkerStyle(health);
            return (
              <div key={health} className="flex flex-col items-center gap-2">
                <MapMarker
                  icon={<span style={{ color: style.glyphColor }}><DroneCardIcon size={20} /></span>}
                  style={style}
                  surfaceSize={36}
                  ringSize={28}
                />
                <span className="text-2xs text-slate-9">{ASSET_HEALTH_LABELS[health]}</span>
              </div>
            );
          })}
        </div>
      ),
    },
    {
      id: 'severity-matrix',
      title: 'Severity & urgency (targets)',
      code: `import { resolveTargetMarkerStyle, resolveThreatGlyph, targetAffiliation } from "@/primitives"

// TargetStateInput is backend-agnostic — plain JSON state.
const state = { status: "event", classifiedType: "car" }  // → CRITICAL
const style = resolveTargetMarkerStyle(state)

<MapMarker
  icon={resolveThreatGlyph(state, style.glyphColor)}
  style={style}
  pulse={targetAffiliation(state) === "hostile"}
  …
/>`,
      render: () => (
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-5">
          {SEVERITY_ORDER.map((sev) => {
            const state = SEVERITY_FIXTURES[sev];
            const style = resolveTargetMarkerStyle(state);
            return (
              <div
                key={sev}
                className="flex flex-col items-center gap-3 rounded-lg border border-white/[0.06] bg-white/[0.03] px-3 py-4"
              >
                <MapMarker
                  icon={resolveThreatGlyph(state, style.glyphColor)}
                  style={style}
                  surfaceSize={42}
                  ringSize={34}
                  pulse={targetAffiliation(state) === 'hostile'}
                />
                <div className="flex flex-col items-center gap-0.5">
                  <span className="text-xs font-semibold text-slate-11">{SEVERITY_LABEL[sev]}</span>
                  <span className="font-mono text-2xs text-slate-9">{SEVERITY_COLOR[sev]}</span>
                  {SEVERITY_PULSE[sev] && (
                    <span className="text-2xs uppercase tracking-wide text-slate-9">pulses</span>
                  )}
                </div>
              </div>
            );
          })}
          {(() => {
            const state: TargetStateInput = { entityStage: 'raw_detection' };
            const style = resolveTargetMarkerStyle(state);
            return (
              <div className="flex flex-col items-center gap-3 rounded-lg border border-white/[0.06] bg-white/[0.03] px-3 py-4">
                <MapMarker
                  icon={resolveThreatGlyph(state, style.glyphColor)}
                  style={style}
                  surfaceSize={42}
                  ringSize={34}
                />
                <div className="flex flex-col items-center gap-0.5">
                  <span className="text-xs font-semibold text-slate-11">Unclassified</span>
                  <span className="font-mono text-2xs text-slate-9">{UNKNOWN_GRAY}</span>
                  <span className="text-2xs uppercase tracking-wide text-slate-9">no ring</span>
                </div>
              </div>
            );
          })()}
        </div>
      ),
    },
    {
      id: 'glyph-routing',
      title: 'Entity glyph routing',
      code: `import { resolveThreatGlyph } from "@/primitives"

resolveThreatGlyph({ classifiedType: "car" }, color)              // vehicle
resolveThreatGlyph({ classifiedType: "drone" }, color, { headingDeg })  // rotated nose
resolveThreatGlyph({ type: "missile" }, color)                    // sensor-type fallback
resolveThreatGlyph({ entityStage: "raw_detection" }, color)       // gray unknown`,
      render: () => (
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-6">
          {([
            { label: 'car · ground_vehicle', el: <CarIcon color="white" size={32} /> },
            { label: 'tank', el: <TankIcon color="white" size={32} /> },
            { label: 'truck', el: <TruckIcon color="white" size={32} /> },
            { label: 'drone · aircraft · bird · uav · naval', el: <DroneIcon color="white" /> },
            { label: 'missile', el: <MissileIcon fill="white" /> },
            { label: 'unclassified unknown', el: <UnknownIcon color="white" size={32} /> },
          ] as { label: string; el: React.ReactNode }[]).map(({ label, el }) => (
            <div
              key={label}
              className="flex flex-col items-center gap-2 rounded-lg border border-white/[0.06] bg-white/[0.03] px-3 py-4 text-center"
            >
              <div className="flex h-10 items-center justify-center">{el}</div>
              <span className="text-2xs leading-tight text-slate-9">{label}</span>
            </div>
          ))}
        </div>
      ),
    },
  ],
};
