/**
 * Generate the registry theme bootstrap from the app's CSS sources.
 *
 * palette.css and theme.css remain the source of truth. This script keeps the
 * shadcn registry payloads in sync by:
 *   1. writing the CSS partial installed by @c2/base
 *   2. refreshing the base/theme cssVars in registry.json
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

const ROOT = join(import.meta.dirname, '..');
const PALETTE_PATH = join(ROOT, 'src/styles/palette.css');
const THEME_PATH = join(ROOT, 'src/styles/theme.css');
const REGISTRY_PATH = join(ROOT, 'registry.json');
const REGISTRY_CSS_PATH = join(ROOT, 'src/registry/c2-theme.css');

const GENERATED_HEADER = `/*
 * GENERATED by scripts/registry-theme.mjs.
 * Source of truth: src/styles/palette.css + src/styles/theme.css.
 *
 * Installed by @c2/base as src/styles/c2-theme.css. Import it from the
 * consuming app's Tailwind entry CSS before installing C2 components.
 */
`;

const CORE_PRIMITIVES = [
  'utils',
  'button',
  'input',
  'card',
  'dialog',
  'select',
  'dropdown-menu',
  'popover',
  'tooltip',
  'badge',
  'separator',
  'tabs',
  'label',
];

const BASE_DEPENDENCIES = [
  'class-variance-authority',
  'clsx',
  'tailwind-merge',
  'tw-animate-css',
  'lucide-react',
];

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function collectVars(css, selector) {
  const vars = new Map();
  const blockPattern = new RegExp(`(?:^|\\n)${escapeRegExp(selector)}\\s*\\{([\\s\\S]*?)\\n\\}`, 'g');
  let blockMatch;
  while ((blockMatch = blockPattern.exec(css)) !== null) {
    const block = blockMatch[1];
    const declPattern = /^\s*--([a-zA-Z0-9-_]+)\s*:\s*([^;]+);/gm;
    let declMatch;
    while ((declMatch = declPattern.exec(block)) !== null) {
      vars.set(declMatch[1], declMatch[2].trim());
    }
  }
  return vars;
}

function mergeVars(...maps) {
  const out = {};
  for (const map of maps) {
    for (const [key, value] of map.entries()) {
      out[key] = value;
    }
  }
  return out;
}

function buildCssVars(paletteCss, themeCss) {
  const dark = mergeVars(collectVars(paletteCss, ':root'), collectVars(themeCss, ':root'));

  // C2 is dark by default. shadcn writes cssVars.light to :root, so the dark
  // token set intentionally populates both scopes; the generated CSS partial
  // carries the separate .light opt-in block from palette.css.
  return {
    light: dark,
    dark,
  };
}

function buildRegistryCss(paletteCss, themeCss) {
  return `${GENERATED_HEADER}
@import "tw-animate-css";

${paletteCss.trim()}

${themeCss.trim()}
`;
}

function buildBaseItem(cssVars) {
  return {
    name: 'base',
    type: 'registry:base',
    title: 'C2 Base',
    description:
      'Dark-default C2 design-system bootstrap: tokens, Tailwind v4 theme CSS, dependencies, aliases, and core primitives.',
    categories: ['core', 'tokens'],
    config: {
      style: 'c2',
      iconLibrary: 'lucide',
      rtl: true,
      tsx: true,
      rsc: false,
      tailwind: {
        baseColor: 'neutral',
        cssVariables: true,
      },
      aliases: {
        components: '@/components',
        ui: '@/components/ui',
        lib: '@/lib',
        hooks: '@/hooks',
        utils: '@/lib/utils',
      },
      registries: {
        '@c2': 'https://c2-hub-three.vercel.app/r/{name}.json',
      },
    },
    dependencies: BASE_DEPENDENCIES,
    registryDependencies: CORE_PRIMITIVES,
    cssVars,
    css: {
      '@import "./styles/c2-theme.css"': {},
    },
    files: [
      {
        path: 'src/registry/c2-theme.css',
        type: 'registry:file',
        target: '~/src/styles/c2-theme.css',
      },
      {
        path: 'src/app/components/ui/utils.ts',
        type: 'registry:file',
        target: '@ui/utils.ts',
      },
    ],
    docs:
      'C2 is dark by default. The generated CSS partial includes a .light opt-in block; add class="light" only around preview surfaces that intentionally need it.',
  };
}

function buildThemeItem(cssVars) {
  return {
    name: 'theme',
    type: 'registry:theme',
    title: 'C2 Theme',
    description:
      'Thin C2 token theme for apps that already have their own shadcn base setup. For new apps, install @c2/base instead.',
    categories: ['core', 'tokens'],
    cssVars,
  };
}

async function main() {
  const [paletteCss, themeCss, registryRaw] = await Promise.all([
    readFile(PALETTE_PATH, 'utf-8'),
    readFile(THEME_PATH, 'utf-8'),
    readFile(REGISTRY_PATH, 'utf-8'),
  ]);
  const registry = JSON.parse(registryRaw);
  const cssVars = buildCssVars(paletteCss, themeCss);

  await mkdir(dirname(REGISTRY_CSS_PATH), { recursive: true });
  await writeFile(REGISTRY_CSS_PATH, buildRegistryCss(paletteCss, themeCss));

  registry.items = [
    buildBaseItem(cssVars),
    buildThemeItem(cssVars),
    ...registry.items.filter((item) => item.name !== 'base' && item.name !== 'theme'),
  ];

  await writeFile(REGISTRY_PATH, `${JSON.stringify(registry, null, 2)}\n`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
