/**
 * GENERATED by scripts/styleguide-manifest.mjs from tokens/core.json +
 * tokens/c2-domain.json — do not edit by hand. Run
 * `node scripts/styleguide-manifest.mjs` to regenerate; `--check` fails CI
 * when this file is stale.
 *
 * The DTCG JSON is the single source of truth; `tokens.ts` consumes the
 * resolved values below so its public exports stay a stable compatibility
 * surface while the underlying values are theme-able from one place.
 */

export interface DesignTokenMeta {
  /** Dot id, e.g. `core.semantic.color.surface.base`. */
  id: string;
  /** CSS custom property, e.g. `--c2-color-surface-base`. */
  cssVar: string;
  /** Resolved value (references followed). */
  value: string;
  type: string;
  /** `primitive` | `semantic` | `dimension` | `domain`. */
  tier: string;
  /** `core` | `domain`. */
  layer: string;
  description: string;
}

/** Flat, ordered token graph — drives the styleguide docs and agent contract. */
export const DESIGN_TOKENS: DesignTokenMeta[] = [
  { id: "core.primitive.color.white", cssVar: "--c2-primitive-color-white", value: "#ffffff", type: "color", tier: "primitive", layer: "core", description: "Pure white. Base for translucent surface overlays." },
  { id: "core.primitive.color.black", cssVar: "--c2-primitive-color-black", value: "#000000", type: "color", tier: "primitive", layer: "core", description: "Pure black. Base for the selection ring tint." },
  { id: "core.primitive.color.surface.0", cssVar: "--c2-primitive-color-surface-0", value: "#141414", type: "color", tier: "primitive", layer: "core", description: "Base — page background and card content area." },
  { id: "core.primitive.color.surface.1", cssVar: "--c2-primitive-color-surface-1", value: "#202020", type: "color", tier: "primitive", layer: "core", description: "Raised — card container and sidebar." },
  { id: "core.primitive.color.surface.2", cssVar: "--c2-primitive-color-surface-2", value: "#272727", type: "color", tier: "primitive", layer: "core", description: "Overlay — borders and dividers, card container fill." },
  { id: "core.primitive.color.surface.3", cssVar: "--c2-primitive-color-surface-3", value: "#2e2e2e", type: "color", tier: "primitive", layer: "core", description: "Inset — icon boxes and closure buttons." },
  { id: "core.primitive.color.surface.4", cssVar: "--c2-primitive-color-surface-4", value: "#353535", type: "color", tier: "primitive", layer: "core", description: "Hover — sensor rows and hover states." },
  { id: "core.primitive.color.neutral.200", cssVar: "--c2-primitive-color-neutral-200", value: "#dee2e6", type: "color", tier: "primitive", layer: "core", description: "High-contrast text — titles, primary values." },
  { id: "core.primitive.color.neutral.500", cssVar: "--c2-primitive-color-neutral-500", value: "#999999", type: "color", tier: "primitive", layer: "core", description: "Low-contrast text — subtitles, captions, metadata." },
  { id: "core.primitive.color.red.base", cssVar: "--c2-primitive-color-red-base", value: "oklch(0.435 0.151 25)", type: "color", tier: "primitive", layer: "core", description: "Resting destructive fill." },
  { id: "core.primitive.color.red.hover", cssVar: "--c2-primitive-color-red-hover", value: "oklch(0.485 0.151 25)", type: "color", tier: "primitive", layer: "core", description: "Destructive hover — one lightness step up." },
  { id: "core.primitive.color.red.active", cssVar: "--c2-primitive-color-red-active", value: "oklch(0.385 0.151 25)", type: "color", tier: "primitive", layer: "core", description: "Destructive pressed — one lightness step down." },
  { id: "core.primitive.color.amber.base", cssVar: "--c2-primitive-color-amber-base", value: "oklch(0.501 0.166 75)", type: "color", tier: "primitive", layer: "core", description: "Resting warning fill." },
  { id: "core.primitive.color.amber.hover", cssVar: "--c2-primitive-color-amber-hover", value: "oklch(0.551 0.166 75)", type: "color", tier: "primitive", layer: "core", description: "Warning hover — one lightness step up." },
  { id: "core.primitive.color.amber.active", cssVar: "--c2-primitive-color-amber-active", value: "oklch(0.451 0.166 75)", type: "color", tier: "primitive", layer: "core", description: "Warning pressed — one lightness step down." },
  { id: "core.semantic.color.surface.base", cssVar: "--c2-color-surface-base", value: "#141414", type: "color", tier: "semantic", layer: "core", description: "Lowest surface — page and card-content background." },
  { id: "core.semantic.color.surface.raised", cssVar: "--c2-color-surface-raised", value: "#202020", type: "color", tier: "semantic", layer: "core", description: "Raised surface — cards, sidebar, code panels." },
  { id: "core.semantic.color.surface.overlay", cssVar: "--c2-color-surface-overlay", value: "#272727", type: "color", tier: "semantic", layer: "core", description: "Container fill, borders, dividers." },
  { id: "core.semantic.color.surface.inset", cssVar: "--c2-color-surface-inset", value: "#2e2e2e", type: "color", tier: "semantic", layer: "core", description: "Recessed wells — icon boxes, closure buttons." },
  { id: "core.semantic.color.surface.hover", cssVar: "--c2-color-surface-hover", value: "#353535", type: "color", tier: "semantic", layer: "core", description: "Hover/active row surface." },
  { id: "core.semantic.color.text.default", cssVar: "--c2-color-text-default", value: "#dee2e6", type: "color", tier: "semantic", layer: "core", description: "Default high-contrast text." },
  { id: "core.semantic.color.text.muted", cssVar: "--c2-color-text-muted", value: "#999999", type: "color", tier: "semantic", layer: "core", description: "Secondary, lower-emphasis text." },
  { id: "core.semantic.color.action.danger.bg", cssVar: "--c2-color-action-danger-bg", value: "oklch(0.435 0.151 25)", type: "color", tier: "semantic", layer: "core", description: "Destructive action background." },
  { id: "core.semantic.color.action.danger.hover", cssVar: "--c2-color-action-danger-hover", value: "oklch(0.485 0.151 25)", type: "color", tier: "semantic", layer: "core", description: "Destructive action hover." },
  { id: "core.semantic.color.action.danger.active", cssVar: "--c2-color-action-danger-active", value: "oklch(0.385 0.151 25)", type: "color", tier: "semantic", layer: "core", description: "Destructive action pressed." },
  { id: "core.semantic.color.action.warning.bg", cssVar: "--c2-color-action-warning-bg", value: "oklch(0.501 0.166 75)", type: "color", tier: "semantic", layer: "core", description: "Warning action background." },
  { id: "core.semantic.color.action.warning.hover", cssVar: "--c2-color-action-warning-hover", value: "oklch(0.551 0.166 75)", type: "color", tier: "semantic", layer: "core", description: "Warning action hover." },
  { id: "core.semantic.color.action.warning.active", cssVar: "--c2-color-action-warning-active", value: "oklch(0.451 0.166 75)", type: "color", tier: "semantic", layer: "core", description: "Warning action pressed." },
  { id: "core.semantic.color.focus.ring", cssVar: "--c2-color-focus-ring", value: "#ffffff", type: "color", tier: "semantic", layer: "core", description: "Focus-visible ring color (applied at reduced opacity by components)." },
  { id: "core.semantic.color.selection.ring", cssVar: "--c2-color-selection-ring", value: "#000000", type: "color", tier: "semantic", layer: "core", description: "Selected-card ring tint (applied at 15% opacity)." },
  { id: "core.semantic.radius.interactive", cssVar: "--c2-radius-interactive", value: "4px", type: "dimension", tier: "semantic", layer: "core", description: "Border radius for all interactive elements — buttons, badges, chips. The system's signature 4px corner." },
  { id: "domain.threat.idle", cssVar: "--c2-threat-idle", value: "#52525b", type: "color", tier: "domain", layer: "domain", description: "No activity — neutral grey." },
  { id: "domain.threat.suspicion", cssVar: "--c2-threat-suspicion", value: "#f59e0b", type: "color", tier: "domain", layer: "domain", description: "Suspected target — amber." },
  { id: "domain.threat.detection", cssVar: "--c2-threat-detection", value: "#fa5252", type: "color", tier: "domain", layer: "domain", description: "Active detection — red." },
  { id: "domain.threat.tracking", cssVar: "--c2-threat-tracking", value: "#fd7e14", type: "color", tier: "domain", layer: "domain", description: "Being tracked — orange." },
  { id: "domain.threat.mitigating", cssVar: "--c2-threat-mitigating", value: "#ef4444", type: "color", tier: "domain", layer: "domain", description: "Jam in progress — bright red." },
  { id: "domain.threat.active", cssVar: "--c2-threat-active", value: "#74c0fc", type: "color", tier: "domain", layer: "domain", description: "Mission active — blue." },
  { id: "domain.threat.resolved", cssVar: "--c2-threat-resolved", value: "#12b886", type: "color", tier: "domain", layer: "domain", description: "Neutralized / resolved — green." },
  { id: "domain.threat.expired", cssVar: "--c2-threat-expired", value: "#3f3f46", type: "color", tier: "domain", layer: "domain", description: "Timed out — dark grey." },
];

/** Resolved CORE token tree (brand-agnostic). */
export const coreTokens = {
  "primitive": {
    "color": {
      "white": "#ffffff",
      "black": "#000000",
      "surface": {
        "0": "#141414",
        "1": "#202020",
        "2": "#272727",
        "3": "#2e2e2e",
        "4": "#353535"
      },
      "neutral": {
        "200": "#dee2e6",
        "500": "#999999"
      },
      "red": {
        "base": "oklch(0.435 0.151 25)",
        "hover": "oklch(0.485 0.151 25)",
        "active": "oklch(0.385 0.151 25)"
      },
      "amber": {
        "base": "oklch(0.501 0.166 75)",
        "hover": "oklch(0.551 0.166 75)",
        "active": "oklch(0.451 0.166 75)"
      }
    }
  },
  "semantic": {
    "color": {
      "surface": {
        "base": "#141414",
        "raised": "#202020",
        "overlay": "#272727",
        "inset": "#2e2e2e",
        "hover": "#353535"
      },
      "text": {
        "default": "#dee2e6",
        "muted": "#999999"
      },
      "action": {
        "danger": {
          "bg": "oklch(0.435 0.151 25)",
          "hover": "oklch(0.485 0.151 25)",
          "active": "oklch(0.385 0.151 25)"
        },
        "warning": {
          "bg": "oklch(0.501 0.166 75)",
          "hover": "oklch(0.551 0.166 75)",
          "active": "oklch(0.451 0.166 75)"
        }
      },
      "focus": {
        "ring": "#ffffff"
      },
      "selection": {
        "ring": "#000000"
      }
    },
    "radius": {
      "interactive": "4px"
    }
  }
} as const;

/** Resolved C2 DOMAIN token tree (tactical, product-specific). */
export const domainTokens = {
  "threat": {
    "idle": "#52525b",
    "suspicion": "#f59e0b",
    "detection": "#fa5252",
    "tracking": "#fd7e14",
    "mitigating": "#ef4444",
    "active": "#74c0fc",
    "resolved": "#12b886",
    "expired": "#3f3f46"
  }
} as const;
